# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^packaging/ucslint/testframework/\
          |^services/univention-ldb-modules/buildtools/\
          |^services/univention-ldb-modules/third_party/
         "
repos:
  - repo: https://git.knut.univention.de/univention/dist/pre-commit-ucr
    rev: '0.0.10'
    hooks:
      - id: ucr-flake8
        additional_dependencies: ["flake8==5.0.4"]
      - id: ucr-ruff
        additional_dependencies: ["ruff==0.1.4"]
      - id: ucr-autopep8
        additional_dependencies: ["autopep8<=2.0.2"]
        stages: [ manual ]
      - id: ucr-ruff-fix
        additional_dependencies: ["ruff==0.1.4"]
        stages: [ manual ]
      - id: ucr-ruff-format-check
        additional_dependencies: ["ruff==0.1.4"]
        stages: [ manual ]
      - id: ucr-ruff-format
        additional_dependencies: ["ruff==0.1.4"]
        stages: [ manual ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-added-large-files
    - id: check-json
      exclude: "/conffiles/.*[.]json$"
    - id: check-xml
      exclude: "/conffiles/.*[.]xml$\
                |^base/univention-app-appliance/\
               "
    - id: check-yaml
      exclude: "/conffiles/.*[.]yaml$"
    - id: check-merge-conflict
    - id: pretty-format-json
      exclude: "/conffiles/.*[.]json$\
               "
      args:
        - --autofix
        - --no-ensure-ascii
    - id: trailing-whitespace
      exclude: "^base/univention-config-registry/tests/unwrap/\
                |^base/univention-lib/unittests/fstab$\
                |^base/univention-system-setup/city-data/.*[.](txt|json)$\
                |^doc/errata/staging/0.*template[.]yaml$\
                |^services/univention-ldb-modules/buildtools/\
                |^services/univention-ldb-modules/third_party/\
                |[.]ai$\
                |[.]csv$\
                |[.]diff$\
                |[.]patch$\
                |[.]svg$\
               "
  - repo: local
    hooks:
      - id: univention-l10n
        name: univention-l10n-build de
        stages: [manual]
        description: univention-l10n
        language: script
        entry: packaging/univention-l10n/univention-l10n-build
        pass_filenames: false
        require_serial: true
        args: [de]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    - id: python-check-blanket-noqa
    - id: python-no-eval
      exclude: "^management/univention-directory-manager-modules/modules/univention/admin/__init__.py\
                |^services/univention-ldb-modules/buildtools/\
                |^services/univention-ldb-modules/third_party/\
                |^test/ucs-test/tests/10_ldap/52listener-filter.py\
                |^packaging/univention-l10n/univention/l10n/umc.py"
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
  - repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    - id: flake8
      exclude: "^oidc/python-keycloak/\
                |^services/univention-ldb-modules/buildtools/\
                |^services/univention-ldb-modules/third_party/\
                |^packaging/ucslint/testframework/\
               "
  - repo: https://git.knut.univention.de/univention/dist/pre-commit-debian.git
    rev: v1.1.0
    hooks:
      - id: debian-control
      - id: debian-changelog
  - repo: https://git.knut.univention.de/univention/dist/pre-commit-ucs.git
    rev: v1.4.0
    hooks:
      - id: ucs-erratum
      - id: missing-executable-flag-for-python-file
      - id: missing-executable-flag-for-shell-file
  - repo: https://git.knut.univention.de/univention/dist/pre-commit-ucs.git
    rev: "9e44eef9a3329c18ecc651041941e73bf369f7d0"
    hooks:
      - id: ucslint-0001-joinscript
      - id: ucslint-0002-copy-paste-errors
      - id: ucslint-0004-ucr
      - id: ucslint-0006-postinst
      - id: ucslint-0007-changelog
      - id: ucslint-0008-translations
      - id: ucslint-0009-python
      - id: ucslint-0010-copyright
        exclude: "^doc/developer-reference/.*$\
                  |^doc/Makefile$\
                  |^doc/manual/images/image-shadow.sh\
                  |^management/univention-directory-listener/debian/tests\
                  |^.gitlab-ci/\
                  |^test/branch-tests/\
                  |^test/product-tests/\
                  |^test/scenarios/\
                  |^test/utils/\
                  |^management/univention-management-console/umc-module-templates/\
                 "
      - id: ucslint-0011-control
        exclude: "^doc/developer-reference/.*$"
      # - id: ucslint-0013-bashism  # too slow
      #   exclude: "^base/univention-lib/shell/base.sh$\
      #             |services/univention-samba4/lib/base.sh$\
      #             |test/product-tests/component/openid-connect.sh$\
      #             |test/scenarios/veyon/utils-veyon.sh$\
      #             |test/ucs-test/lib/ldap.sh$\
      #             |test/ucs-test/lib/samba.sh$\
      #             |test/ucs-test/tests/09_updater/pool.sh$\
      #             |test/ucs-test/tests/52_s4connector/s4connector.sh$\
      #             |test/utils/base_appliance.sh$\
      #             |test/utils/ram/utils-ram.sh$\
      #            "
      - id: ucslint-0014-depends  # requires to be run on the same Debian version
      - id: ucslint-0015-fuzzy-names
      - id: ucslint-0016-deprecated
      - id: ucslint-0017-shell
      - id: ucslint-0018-debian
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.4'
    hooks:
      - id: ruff
        exclude: "^oidc/python-keycloak/\
                  |^services/univention-ldb-modules/buildtools/\
                  |^services/univention-ldb-modules/third_party/\
                  |^packaging/ucslint/testframework/\
                 "
      - id: ruff
        alias: "ruff-fix"
        stages: [ manual ]
        args: ["--fix", "--unsafe-fixes"]
        exclude: "^oidc/python-keycloak/\
                  |^services/univention-ldb-modules/buildtools/\
                  |^services/univention-ldb-modules/third_party/\
                  |^packaging/ucslint/testframework/\
                 "
      - id: ruff
        alias: "ruff-statistics"
        stages: [ manual ]
        args: ["--statistics"]
        exclude: "^oidc/python-keycloak/\
                  |^services/univention-ldb-modules/buildtools/\
                  |^packaging/ucslint/testframework/\
                 "
      - id: ruff-format
        alias: "ruff-format"
        stages: [ manual ]
        exclude: "^oidc/python-keycloak/\
                  |^services/univention-ldb-modules/buildtools/\
                  |^packaging/ucslint/testframework/\
                 "
      - id: ruff-format
        alias: "ruff-format-check"
        stages: [ manual ]
        args: ["--check"]
        exclude: "^oidc/python-keycloak/\
                  |^services/univention-ldb-modules/buildtools/\
                  |^packaging/ucslint/testframework/\
                 "
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        entry: isort -c
        exclude: "^oidc/python-keycloak/\
                  |^services/univention-ldb-modules/buildtools/\
                  |^services/univention-ldb-modules/third_party/\
                  |^packaging/ucslint/testframework/\
                 "
      - id: isort
        alias: "isort-fix"
        stages: [ manual ]
        entry: isort
        exclude: "^oidc/python-keycloak/\
                  |^services/univention-ldb-modules/buildtools/\
                  |^services/univention-ldb-modules/third_party/\
                  |^packaging/ucslint/testframework/\
                 "
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
        args: ["-d"]
        exclude: "^oidc/python-keycloak/\
                  |^services/univention-ldb-modules/buildtools/\
                  |^services/univention-ldb-modules/third_party/\
                  |^packaging/ucslint/testframework/\
                  "
    -   id: autopep8
        alias: "autopep8-fix"
        stages: [ manual ]
        args: ["-i"]
        exclude: "^oidc/python-keycloak/\
                  |^services/univention-ldb-modules/buildtools/\
                  |^services/univention-ldb-modules/third_party/\
                  |^packaging/ucslint/testframework/\
                  "
