include:
  - project: 'univention/documentation/sphinx-docker'
    file: 'pipeline/sphinx.yml'

.publish:
  interruptible: false
  variables:
    GIT_STRATEGY: none

review:
  stage: merge
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
  extends: .publish
  tags:
    - omar
  script:
    - rsync -av --delete out/ "/var/univention/buildsystem2/test_mirror/ftp/download/docs.$CI_COMMIT_REF_SLUG"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://apt.knut.univention.de/download/docs.$CI_COMMIT_REF_SLUG/
    on_stop: stop_review
    auto_stop_in: 1 week

stop_review:
  stage: merge
  variables:
    GIT_STRATEGY: none
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
  needs:
    - review
  allow_failure: true
  extends: .publish
  tags:
    - omar
  script:
    - rm -rf "/var/univention/buildsystem2/test_mirror/ftp/download/docs.$CI_COMMIT_REF_SLUG"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

staging:
  stage: merge
  extends: .publish
  tags:
    - omar
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - rsync -av --delete out/ /var/univention/buildsystem2/test_mirror/ftp/download/docs
  environment:
    name: staging
    url: http://apt.knut.univention.de/download/docs/
