default:
  artifacts:
    expire_in: 1 day
  interruptible: true
  retry:
    max: 2
    when:
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure

variables:
  ucs: 507
  DOC_TARGET_VERSION: "5.0"
  CHANGELOG_TARGET_VERSION: "5.0-7"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_DEPTH: "3"
  DEB: docker-registry.knut.univention.de/phahn/ucs-debbase:$ucs
  PIP_BUILD_TOOLS: docker-registry.knut.univention.de/knut/pip-builder:branch-jlohmer-pip-builder
  APTLY: http://omar.knut.univention.de:11620/api
  APT: http://omar.knut.univention.de/build2/git
