product: ucs
release: "5.0"
version: [1]
scope: ucs_5.0-0-errata5.0-1
src: univention-config-registry
fix: 
desc: |
 This update addresses the following issue:
 * Notify caller when `UCR` variable changes and service restart is
   expected to be performed.
bug: [51125]
